# Generated by Django 3.1.2 on 2020-10-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('jDesc', models.CharField(max_length=100)),
                ('resp', models.CharField(max_length=100)),
                ('salaryDesc', models.CharField(max_length=100)),
            ],
        ),
    ]
