# Generated by Django 3.1.2 on 2020-10-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpingRecruiters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidateName', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=1500)),
                ('highestQual', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=1500)),
                ('contact', models.CharField(max_length=13)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpingRecruiters.newjob')),
            ],
        ),
    ]
